// <auto-generated />
namespace NewApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RatingAddintoMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RatingAddintoMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "201910011955138_Rating-Add-into-Movie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
